spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Shanghai
  redis:
    database: 2
    host: localhost
    port: 6379
    timeout: 200s
    lettuce:
      pool:
        max-wait: 60s
        max-idle: 8


jwt:
  secret: qwwewe
  expiration: 3600000 # 一小时
  header: jwt-header
server:
  port: 8000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
